export const TagList = [
  { id: 0, type: "Games" },
  { id: 1, type: "Business" },
  { id: 2, type: "Food" },
  { id: 3, type: "Travelling" },
  { id: 4, type: "Tech" },
  { id: 5, type: "Mental" },
  { id: 6, type: "Fitness" },
  { id: 7, type: "Nightlife" },
  { id: 8, type: "Religion" },
  { id: 9, type: "Sport" },
  { id: 10, type: "Health" },
  { id: 11, type: "Architecture" },
  { id: 12, type: "Coffee" },
  { id: 13, type: "Gadget" },
  { id: 14, type: "Music" },
  { id: 15, type: "NSFW" },
  { id: 16, type: "Photography" },
  { id: 17, type: "Crypto" },
  { id: 18, type: "Math" },
  { id: 19, type: "Socmed" },
  { id: 20, type: "Nature" },
];
